GoogleCloudPlatform/google-fluentd

config/software/ruby.rb
This should fix the omnibus build.
=> Fix the Ruby patch name.

templates/etc/td-agent/td-agent.conf, templates/etc/td-agent/td-agent.conf.tmpl
=> Updated configuration to spawn multiple threads for processing.

config/software/fluentd.rb
I have tried to use second output but I couldn't.
It seems to need https://github.com/fluent/fluentd/pull/1283.
=> Update fluentd to v0.14.14

windows-installer/fluent-template.conf, windows-installer/setup.nsi
This will allow users to expand on the current config
=> Add a directory where fluentd configs can be placed for the windows agent to consume.

windows-installer/setup.nsi
fluentd now allows for configurable service names.
=> Change Windows Service Name to Stackdriver Logging

windows-installer/setup.nsi
Without this the uninstall will fail.
I forgot to send this yesterday but this is already in the next release.
=> Pass the service name to the uninstall step for the Windows Installer

config/software/ruby.rb, config/software/td-agent-cleanup.rb, config/software/td-agent-files.rb, config/software/td-agent-ui.rb, config/software/td.rb
Some file paths needed to be updated when #43 was committed.
=> Update gems dir to 2.2 from 2.1

config/projects/google-fluentd.rb
Includes bundling gem version 0.6.4 as well as upgrade of default packaged Ruby to 2.2.7.
=> Bump version to 1.5.17.

templates/etc/td-agent/td-agent.conf, templates/etc/td-agent/td-agent.conf.tmpl, windows-installer/fluent-template.conf
This depends on https://github.com/GoogleCloudPlatform/google-fluentd/pull/65.
=> Turn on partial_success by default.

config/software/td-agent.rb, config/software/xz.rb
Use URL to tarballs hosted on GCS bucket.
=> Add vendored xz utils file to override download location. 

templates/etc/init.d/rpm/td-agent
This should work now. Merging into an "official" `sles12-build` branch. Will reconcile and merge into `master` later.
=> Support for SLES 12.

templates/etc/td-agent/td-agent.conf, templates/etc/td-agent/td-agent.conf.tmpl, windows-installer/fluent-template.conf
This depends on https://github.com/GoogleCloudPlatform/google-fluentd/pull/111.
=> Add insertIds by default.

windows-installer/generate_sdl_agent_exe.ps1
=> Use Invoke-WebRequest instead of WebClient.DownloadFile to handle redirects.

windows-installer/generate_sdl_agent_exe.ps1
=> Respect PowerShell operator precedence.

windows-installer/generate_sdl_agent_exe.ps1
=> Bump google-protobuf to 3.7.1 on Windows as well to pick up a fix for the Windows startup crash.

build/x86_64_centos6/Dockerfile, build/x86_64_centos7/Dockerfile, build/x86_64_centos8/Dockerfile, build/x86_64_debian/Dockerfile, build/x86_64_sles12/Dockerfile
SLES 15 requires Ohai with higher version which then requires ruby >=2.5
=> Upgrade Build Container Ruby Version to 2.5.3

config/projects/google-fluentd.rb, config/software/ruby.rb, config/software/td-agent-cleanup.rb, config/software/td-agent-files.rb, config/software/td-agent-ui.rb, config/software/td.rb
We see reduce memory usage.
This passed local build tests.
=> Bumped Ruby version to 2.6.5.

build/x86_64_centos6/Dockerfile, build/x86_64_centos7/Dockerfile, build/x86_64_centos8/Dockerfile, build/x86_64_debian/Dockerfile, build/x86_64_sles12/Dockerfile
We now have successful Cloud Build trigger executions.
=> Fix build Dockerfiles and make them uniform

plugin_gems.rb
This matches change in output plugin here: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/369
=> Bump opencensus-stackdriver to 0.3.1.

config/software/fluentd.rb
Verified that everything looks good.
CPU: 
RSS:
Throughput:
=> Upgrade Fluentd version to 1.7.4.

windows-installer/generate_sdl_agent_exe.ps1
Similar to https://github.com/GoogleCloudPlatform/google-fluentd/pull/245.
=> Update Fluentd to 1.7.4 for Windows.

Gemfile, Gemfile.lock, config/software/ruby.rb
Also revert #257 and upgrade omnibus to 7.0.9.
=> Upgrade omnibus-software to pick up chef/omnibus-software#1178.

templates/etc/init.d/deb/td-agent, templates/etc/init.d/rpm/td-agent
- supervisor mode brings more benefits in things like restarting workers on-crash
tested in:
=> Revert changes on removing supervisor mode.

templates/etc/init.d/deb/td-agent, templates/etc/init.d/rpm/td-agent
This reverts commit 8e0dc7ef82f66ac360180986ec11f00d6b43b389.
=> Revert "Revert changes on removing supervisor mode. (#295)"

windows-installer/fluent-template.conf
=> Set the default value of use_grpc back to true now that the grpc issue has been fixed.

core_gems.rb
This picks up https://github.com/protocolbuffers/protobuf/pull/8461. More context in b/182381016#comment5.
=> Upgrade google-protobuf to 3.15.8.

config/projects/google-fluentd.rb, config/software/fluentd.rb, windows-installer/generate_sdl_agent_exe.ps1
=> Upgrade fluentd to v1.12.3 (from v1.11.2).

docker/Dockerfile
@hsmatulisgoogle FYI, as this touches the same file as #330.
=> Switch from install-logging-agent.sh to add-logging-agent-repo.sh.

config/projects/google-fluentd.rb, config/software/fluentd.rb, docker/Dockerfile, plugin_gems.rb, windows-installer/generate_sdl_agent_exe.ps1
This reverts parts of commit 86aea0c2687ec75a54928d08677a8d2f5062bbc2.
=> Restore versions after accidental changes in #330.

config/projects/google-fluentd.rb
=> Add sysvinit-tools dependency on SLES.

config/software/ruby.rb
=> Bump Ruby version to 2.6.9.

core_gems.rb
To match https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/486.
=> Upgrade to grpc-1.45.0 and google-protobuf-3.20.0

core_gems.rb, windows-installer/generate_sdl_agent_exe.ps1
Updating DevKit installer to version 2.7.6.
Bumped msgpack version to be compatible with new ruby version.
* http://b/265344269
=> Updating windows ruby devkit installer.

Gemfile, build/x86_64_amzn-2016.09/Dockerfile, build/x86_64_centos6/Dockerfile, build/x86_64_centos7/Dockerfile, build/x86_64_centos8/Dockerfile, build/x86_64_debian/Dockerfile, build/x86_64_sles12/Dockerfile, build/x86_64_sles15/Dockerfile, config/projects/google-fluentd.rb, config/software/ruby.rb, config/software/td-agent-cleanup.rb, config/software/td-agent-files.rb, config/software/td-agent-ui.rb, config/software/td.rb, core_gems.rb, plugin_gems.rb, windows-installer/generate_sdl_agent_exe.ps1
[b/254273286](http://b/254273286).
Depends on https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/504.
=> Bump default Ruby version to 3.1.3.

build/x86_64_amzn-2016.09/Dockerfile, build/x86_64_centos6/Dockerfile, build/x86_64_centos7/Dockerfile, build/x86_64_centos8/Dockerfile, build/x86_64_debian/Dockerfile, build/x86_64_sles12/Dockerfile, build/x86_64_sles15/Dockerfile
[b/276374852](http://b/276374852).
=> Update the rvm checksum in build containers.

core_gems.rb, plugin_gems.rb, windows-installer/generate_sdl_agent_exe.ps1, windows-installer/setup.nsi
[b/288334380](http://b/288334380).
=> Switch the Windows package to 64-bit Ruby 3.1.2.

docker/Dockerfile
=> Using newer image as base for docker container

config/projects/google-fluentd.rb
=> Require systemd-sysvcompat on SUSE

build/x86_64_centos8/Dockerfile, build/x86_64_debian/Dockerfile, build/x86_64_sles12/Dockerfile, build/x86_64_sles15/Dockerfile, config/projects/google-fluentd.rb, config/software/ruby.rb, windows-installer/generate_sdl_agent_exe.ps1
Updating to the latest patch version of 3.3.x to pick up the patch for [CVE-2025-24294](https://www.ruby-lang.org/en/news/2025/07/08/dos-resolv-cve-2025-24294)
=> Update Ruby to version 3.3.9
