config/projects/google-fluentd.rb, config/software/ruby.rb
* b/32656946 revert default ruby version to v2.1.8
There is a bug (https://github.com/google/protobuf/commit/866d3e5327d11b6846edb1b65f73673008a43ed2) in protobuf to fix support for Ruby version like v2.1.10. And it’s released in protobuf v3.1.0. However the latest gRPC v1.0.1 we are using in the logging agent is still using protobuf v3.0.2.
In the long term, we should upgrade to a gRPC version with protobuf (>= v3.1.0). Or we can try to force the protobuf version to be >= v3.1.0 at run time (not sure if that is feasible yet).
In the short term, we would leave the Ruby default version to 2.1.8.
=> gRPC support fix for logging agent

config/software/fluentd.rb
Updated version of fluentd to v0.14.8 for the google-fluentd Logging agent.
=> Bumped fluentd version to v0.14.8

core_gems.rb
Fixing current warnings when restarting the agent. 
I do remember there being an issue with json-1.8.0-1.8.1 but cannot find a pull request...
I've put `puts caller` in the offending files producing json warnings and got the following diff:
```
< /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/ext.rb:13:in `<module:Ext>'
< /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/ext.rb:12:in `<module:JSON>'
< /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/ext.rb:9:in `<top (required)>'
< /opt/google-fluentd/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
< /opt/google-fluentd/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
< …
```
=> Bump json to 1.8.3 to fix warnings

windows-installer/generate_sdl_agent_exe.ps1, windows-installer/setup.nsi, windows-installer/stackdriver_util.nsh
The agent version is now visible during the entire install and uninstall process as well as written to the registry.
Previously we wrote to SHCTX (shell context) which could write to the local machine or current user.  We should always write to the local machine as this is reading event logs which is machine wide.
=> Add the agent version to the installer and always write to the HKLM registry

windows-installer/fluent-template.conf
Parse the time the log was generated into a format the google cloud logging plugin can understand.
This will ensure the log appears with the correct time.
=> Properly parse windows event log time stamps 

windows-installer/generate_sdl_agent_exe.ps1, windows-installer/setup.nsi
This was previously not allowed due to a bug in fluentd.  This was fixed in the most recent release and can now be allowed.
=> Allow the Logging Agent Installer to install to any location

templates/etc/td-agent/td-agent.conf, templates/etc/td-agent/td-agent.conf.tmpl
Sending smaller batches should avoid delays in batch ingestion.
=> Halve the default batch size to tune API latency.

config/software/jemalloc.rb
www.canonware.com seems to be down for a while. Making the change to allow builds complete.
=> Change repository for jemalloc from canonware.com to pkgs.fedoraproject.org

templates/etc/init.d/deb/td-agent, templates/etc/init.d/rpm/td-agent
Setting a timeout allows the fluentd service to start even if the metadata service is unavailable. This would otherwise result in the process hanging.
=> Add timeout to metadata server check

docker/Dockerfile, docker/run.sh
Incorporating the run.sh that can be found in fluentd-gcp's image into ours to handle journald and systemd.
=> Add a run.sh command to manage journald and systemd directories.

templates/etc/td-agent/td-agent.conf, templates/etc/td-agent/td-agent.conf.tmpl, windows-installer/fluent-template.conf
Right now the Logging Agent by default will retry forever if any of the following errors occur:
For gRPC:
```
GRPC::Internal,
GRPC::Unimplemented,
GRPC::Unavailable,
GRPC::DeadlineExceeded
```
For REST:
```
Google::Apis::ServerError
```
The intention is guarantee log delivery. Yet during incidents like Logging API server going down or experiencing severe latency, this "retrying forever" behavior might be an issue, consuming too much CPU and even bringing down customer's applications.
We should by default enforce some reasonable retry limit and let users opt in retrying forever if they really want to.
Sample configuration to consider (exact numbers TBD):
```
disable_retry_limit false
retry_limit 8
retry_wait 1
max_retry_wait 300
```
With the configuration above, if a server is down during …
=> Enforce retry limit by default and let users opt in forever retries if needed.

config/software/jemalloc.rb
b/73729943.
Our integration test caught `pthread_create` failures when installing the agent on `ubuntu-1404-trusty`. So far the issue is isolated to only `ubuntu-1404-trusty`.
Errors
```
==============================================================================
Starting installation of google-fluentd
==============================================================================
Installing agents for Debian or Ubuntu.
OK
Selecting previously unselected package google-fluentd.
(Reading database ... 42945 files and directories currently installed.)
Preparing to unpack .../google-fluentd_1.5.28-1_amd64.deb ...
Unpacking google-fluentd (1.5.28-1) ...
Selecting previously unselected package google-fluentd-catch-all-config.
Preparing to unpack .../google-fluentd-catch-all-config_0.7_all.deb …
```
=> Change jemalloc version pin from 5.0.1 to 4.5.0.

docker/Dockerfile
This fixes CVEs in `stretch-20180312`.
=> Update Debian base image to stretch-20180426.

docker/Dockerfile
Pin systemd-journal to < 1.3.2 until https://github.com/ledbettj/systemd-journal/issues/79 is fixed.
=> Pin systemd-journal to 1.3.0.

windows-installer/generate_sdl_agent_exe.ps1
This is a follow-on to #148 — turns out the download was silently failing all along until we turned on error handling.
=> Update NSISunzU download location to avoid redirects.

templates/etc/init.d/rpm/td-agent
This fixes "sudo service google-fluentd restart" and "sudo service google-fluentd configtest".
=> Don't pass start_daemon args to the agent itself -- they're not compatible.

plugin_gems.rb
These gems are needed to populate Kubernetes metadata (e.g. pod labels) and transform the data to be something the fluent_plugin_google_cloud gem understands (e.g. "logging.googleapis.com/labels"), so that we can send the correct metadata to Stackdriver.
=> Add dependencies fluent-plugin-kubernetes_metadata_filter and fluent-plugin-record-modifier.

config/projects/google-fluentd.rb, config/software/ruby.rb, config/software/td-agent-cleanup.rb, config/software/td-agent-files.rb, config/software/td-agent-ui.rb, config/software/td.rb
This reverts commit 352965c177630fca75e973d22486834831d4db44.
The package doesn't build with Ruby 2.5, because of
```
/opt/google-fluentd/embedded/bin/gem install nokogiri -- --use-system-libraries --with-xml2-lib=/opt/google-fluentd/embedded/lib --with-xml2-include=/opt/google-fluentd/embedded/include/libxml2 --with-xslt-lib=/opt/google-fluentd/embedded/lib --with-xslt-include=/opt/google-fluentd/embedded/include/libxslt --with-iconv-dir=/opt/google-fluentd/embedded --with-zlib-dir=/opt/google-fluentd/embedded
ERROR:  While executing gem ... (ArgumentError)
wrong number of arguments (given 1, expected 0)
```
=> Roll back "Update default embedded Ruby version from 2.4 to 2.5. (#172)"

windows-installer/generate_sdl_agent_exe.ps1
This is a follow-on to #176 that fixes the devkit installation commands. It also upgrades fluentd to 1.4.2 (#166) and other gem dependencies (#179).
=> Fix Windows build with Ruby 2.5.

windows-installer/generate_sdl_agent_exe.ps1
Fixes breakage introduced by #181.
=> Look up the eventlog gem path programmatically, so we don't forget to update it again.

windows-installer/generate_sdl_agent_exe.ps1
A follow-on to #176 and #181, which accidentally left them in.
=> Remove unneeded Ruby dev kit files.

windows-installer/setup.nsi
A follow-on to #181 and #183. This makes the installer work again.
=> On Windows, create the main install directory before extracting files.

README.md, docker/Dockerfile
This fixes: 
CVE-2017-15804
CVE-2017-15670
CVE-2018-11236
CVE-2017-16997
CVE-2018-15686
CVE-2017-1000408
CVE-2017-18269
=>  Update base docker image to 9.9-slim for security fixes.

docker/Dockerfile
`MALLOC_ARENA_MAX=2` reduces the number of arenas per threads. This brings the memory usage down which is a good tradeoff for a daemon deployed widely. It may slow the program down by increasing lock contention, but that seems unlikely in a low-thread application, and we haven't seen CPU increase in our load tests.
More details about this change: https://www.speedshop.co/2017/12/04/malloc-doubles-ruby-memory.html
@igorpeshansky you were selected as a reviewer by pRNG.
=> Improve memory allocation strategy

windows-installer/generate_sdl_agent_exe.ps1
This fixes the following error:
```
Exception calling "CreateFromDirectory" with "2" argument(s): "Access to the
path 'C:\GoogleStackdriverLoggingAgent\rubyinstaller.exe' is denied."
At T:\src\google-fluentd\windows-installer\generate_sdl_agent_exe.ps1:180
char:1
```
=> Set BASE_INSTALLER_DIR to current location instead of C:

build/x86_64_sles12/Dockerfile
opensuse images were removed in favor of the opensuse/leap and opensuse/tumbleweed images provided and maintained by the openSUSE Project release team.
https://build.opensuse.org/package/show/Virtualization:containers:images:openSUSE-Leap-42.3/openSUSE-Leap-42.3-container-image
=> Fix sles-42.3 image cannot be found error

plugin_gems.rb
The new version is incompatible with fluent-plugin-prometheus, and it's causing runtime errors. Unfortunately our presubmit tests don't seem to catch the fact that it violates the requirements in the fluent-plugin-prometheus gemspec.
=> Downgrade prometheus-client

bin/gem_installer, core_gems.rb, lib/gems_parser.rb, plugin_gems.rb, windows-installer/generate_sdl_agent_exe.ps1
This change bumps the version of fluentd and of some gems on the Windows side, as now we ship the same in both platforms.
I verified that the installer gives a working agent: I installed the agent and immediately saw logs in the Stackdriver UI.
=> Share the list of gem dependencies between Linux and Windows

plugin_gems.rb
This picks up https://github.com/fluent/fluent-plugin-windows-eventlog/pull/34.
=> Upgrade fluent-plugin-windows-eventlog gem version to 0.4.4.

templates/etc/td-agent/td-agent.conf, templates/etc/td-agent/td-agent.conf.tmpl
This change will use OpenCensus for exporting the metrics under the `agent.googleapis.com/agent` prefix to Stackdriver. This makes monitoring work out-of-the-box, as opposed to the previous mechanism, which relied on either a Prometheus collector or the Stackdriver Monitoring agent.
I successfully tested this on a fresh installation early last week. All the backend changes are in place.
@igorpeshansky @qingling128 can you please review and confirm that these files are used by the GCE packages?
=> Enable opencensus for core Google FluentD metrics

templates/etc/init.d/deb/td-agent, templates/etc/init.d/rpm/td-agent
This brings the memory usage down which is a good tradeoff for a daemon deployed widely. It may slow the program down by increasing lock contention, but that seems unlikely in a low-thread application, and we haven't seen CPU increase in our load tests.
We've been setting this in our container image for a couple months.
More details about this change: https://www.speedshop.co/2017/12/04/malloc-doubles-ruby-memory.html
=> MALLOC_ARENA_MAX=2 reduces the number of arenas per threads.

templates/etc/init.d/deb/td-agent, templates/etc/init.d/rpm/td-agent
This saves ~60MB with the following configuration, which is similar to our default configuration. Without supervisor FluentD can only use one worker, but that is the only configuration we support. This is easy to roll back if we start supporting multiple workers in the future.
```
<match fluent.**>
@type null
</match>
<source>
@type systemd
read_from_head true
tag "systemd"
<storage>
@type local
path journald-cursor.json
</storage>
</source>
<match **>
@type google_cloud
buffer_chunk_limit 1M
flush_interval 5s
num_threads 8
use_grpc true
</match>
```
The pidfile change is needed because of a bug in FluentD that breaks the `--daemon` features when `--no-supervisor` option is used. See https://github.com/fluent/fluentd/issues/2735.
=> Disable fluentd supervision.

templates/etc/init.d/deb/td-agent, templates/etc/init.d/rpm/td-agent
This flag breaks `--dry-run`, which is used by `service google-fluentd configtest`.
Supersedes #229
=> Only pass `--no-supervisor` on real start

plugin_gems.rb
The output plugin (fluent-plugin-google-cloud) is the only thing that uses them and it handles those dependencies itself ([gemspec](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/fluent-plugin-google-cloud.gemspec)).
Reverts #216.
=> Remove direct dependencies on OpenCensus gems.

docker/Dockerfile
=> Clean up Dockerfile; no need to remove extraneous gems -- they are no longer installed.

plugin_gems.rb
This is to pick up https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/214 and https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/219 fixes.
=> Upgrade fluent-plugin-kubernetes_metadata_filter gem to 2.4.5.

build/x86_64_centos6/Dockerfile, build/x86_64_centos7/Dockerfile, build/x86_64_centos8/Dockerfile, build/x86_64_debian/Dockerfile, build/x86_64_sles12/Dockerfile, build/x86_64_sles15/Dockerfile
Turned out that the older distros require `--keyserver hkp://keys.gnupg.net`. Adding `--keyserver hkp://keys.gnupg.net` across the board for consistency.
=> Align rvm installation commands across distros and set disable-ipv6.

build/x86_64_centos6/Dockerfile
The default git version on CentOS 6 is too old after all.
=> Reinstate git installation from rpmforge-extras.

plugin_gems.rb
Docker 1.13 changed the way how it handle logs: entries longer than 16k bytes will be split to a number of entries with size <=16k. This causes a number of problems for our customers using Stackdriver like:
- fragmented log lines
- broken jsons
This aims at bundling that plugin into our package to make it easier for customer who is impacted to concatenate the logs.
=> Bundle fluent-plugin-concat plugin into the package to deal with Docker log split issue.

config/projects/rpm/google-fluentd-start-service.spec
This package will start the `google-fluentd` service automatically when installed.
=> Add an RPM helper package to automatically start the agent service.

config/projects/google-fluentd.rb, plugin_gems.rb
Pull in this [`fluent-plugin-google-cloud` version bump](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/411) that includes [new metric configuration options](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/410) and bump minor version for `google-fluentd` because of it.
=> Bump minor version of google-fluentd and output plugin for next release.

plugin_gems.rb
Reverts part of 0123419ace5ee54de5d8e62e0be0e9fc89fdc772 (#270).
=> Revert fluent-plugin-google-cloud version bump to the last released version.

bin/gem_downloader
This improves the error message when an invalid gem version is specified.
Before this PR:
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
121   243    0   243    0     0   4538      0 --:--:-- --:--:-- --:--:--  5400
ERROR:  While executing gem ... (ArgumentError)
"ge><Requ" is not an octal string
```
After this PR:
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
ERROR:  Could not find a valid gem …
```
=> Surface curl errors when downloading gems.

windows-installer/generate_sdl_agent_exe.ps1
`grpc` version 1.30.1 is not compatible with the current 2.5.5 ruby, which couldn't load or find grpc's dynamic core (LoadError).
=> Upgrade ruby to 2.6.5 on windows

core_gems.rb
Tested internally that it can build the exe. See internal bug for the result.
=> Upgrade cool.io version for compatibility with Ruby 2.6.5

docker/Dockerfile
The current debian 9 base image was last updated over a year ago, and vulnerabilities have been found in several packages. Using a Google managed base image that is regularly rebuilt with up to date packages allows rebuilding the image to pick up the security fixes.
=> Update base docker image to debian:9.13-slim

config/projects/google-fluentd.rb, config/software/fluentd.rb, windows-installer/generate_sdl_agent_exe.ps1
Tested the current release against a new agent which includes the changes in this PR, plus the same fluentd update in the output plugin (https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/418). Metrics look good:
CPU
RSS
Throughput
=> Upgrade fluentd to v1.11.2 (from v1.7.4).

windows-installer/setup.nsi
Using flag introduced in fluent/fluentd#3037. 
Built test agent/installer off of this branch and tested it in a Windows VM. Confirmed that the startup type is updated as expected:
=> Set Windows agent startup type to 'Automatic (Delayed Start)'.

plugin_gems.rb
… to fix issues with pod and namespace watches.
Issues fixed in fluent-plugin-kubernetes_metadata_filter v2.5.2:
Add watch 410 Gone response handling by Ghazgkull · Pull Request #243 · fabric8io/fluent-plugin-kubernetes_metadata_filter
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/243
Add 410 Gone handling for namespace watch by Ghazgkull · Pull Request #247 · fabric8io/fluent-plugin-kubernetes_metadata_filter
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/247
=> Bump fluent-plugin-kubernetes_metadata_filter to v2.5.2

templates/package-scripts/td-agent/rpm/posttrans
This will start service when install or upgrade.
This will keep the service running even when upgrading fails google-fluentd due to then transient LoadError
(I have tested in internal bug ticket.)
=> Create posttrans to start service

plugin_gems.rb, windows-installer/generate_sdl_agent_exe.ps1
- generate*.ps1:
This is to fix the missing dll which causes LoadError on winevt_so
See similar issues here: https://github.com/fluent-plugins-nursery/td-agent-builder/issues/98
This change is inspired by:  https://github.com/fluent-plugins-nursery/td-agent-builder/pull/103
- plugin_gems.rb:
After all the try and trials that i found during the 'joy' of experimenting built pkgs with missing deps that finally found one that works well.
Note some deps are devlopement gem for fluent-plugin-windows-eventlog: https://github.com/fluent/fluent-plugin-windows-eventlog/blob/master/fluent-plugin-winevtlog.gemspec
Note: we add support for eventlog2 but we don't support the eventlog2 configuration yet. You are on your own to deal with it. As supporting eventlog2 will be a backward incompatible change …
=> Add additional dependencies that are needed to support custom windows_eventlog2 config

templates/etc/init.d/deb/td-agent, templates/etc/init.d/rpm/td-agent
supervisor mode is valuable in bringing back dead workers
This reverts #225 and #230.
For centos7:
For debian9:
For sles12:
=> Add supervisor mode back

windows-installer/fluent-template.conf
This is to work around the grpc bug (b/174475386).
=> Set use_grpc to false in the default Windows config.

templates/etc/td-agent/td-agent.conf, templates/etc/td-agent/td-agent.conf.tmpl, templates/package-scripts/td-agent/deb/postinst, templates/package-scripts/td-agent/rpm/post
This goes together with https://github.com/GoogleCloudPlatform/fluentd-catch-all-config/pull/34.
The use cases we need to cover:
Case 1
Users install the google-fluentd package only. They may:
* Modify the google-fluentd.conf file (including making it include more directories / files)
* Add additional files to the conf.d folder
* Add additional files in other folders
In this case, the baseline configs should always only include the original google-fluentd.conf
Case 2
Users install both the google-fluentd package and the catch-all-config package. They may:
* Modify the google-fluentd.conf file (including making it include more directories / files)
* Modify existing files in the conf.d folder
* Add additional files to the conf.d folder
* Add additional files in other folders
In this case, …
=> Init baseline configs and add the config to analyze config usage.

build/x86_64_centos6/Dockerfile
CentOS 6 is now out-of-support, so the repos moved from `mirror.centos.org` to `vault.centos.org`.
=> Update repo URLs for the deprecated CentOS 6 repos.

Gemfile
The [latest bundler 2.2.4](https://rubygems.org/gems/bundler/versions/2.2.4) causes an error below, thus pining the version back to 2.2.3
```
Fetching https://github.com/chef/omnibus.git
Unknown option: -C
usage: git [--version] [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
[-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
[--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
[-c name=value] [--help]
<command> [<args>]
Retrying `git -C /main/google-fluentd clone https://github.com/chef/omnibus.git /usr/local/rvm/gems/ruby-2.5.3/cache/bundler/git/omnibus-dae08cbdfc40f037c88b5de320377a72807a8770 --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone https://github.com/chef/omnibus.git …
```
=> Pin bundler version to 2.2.3

Gemfile
Reverts GoogleCloudPlatform/google-fluentd#310
This doesn't pin the version of bundler itself. Gemfile is used for bundle tool.
=> Revert "Pin bundler version to 2.2.3"

templates/package-scripts/td-agent/deb/postinst, templates/package-scripts/td-agent/rpm/post
Fluentd `includes` can take relevant path. And we ended up putting the baseline config files under `/etc/google-fluentd/baseline/config.d/*.conf`. The sed replace is no longer needed. Tested: b/178038663
=> Remove the baseline sed commands to align the paths.

core_gems.rb, windows-installer/fluent-template.conf
This reverts commit 3ad481bb6344f376e11bb9bfe8ced71f26fff775, and also pin google-protobuf at 3.14.0.
The `google-protobuf` `3.15.0` version includes the segmentation fault fix, but introduced memory and cpu usage performance regression. Detailed reasons in b/181210044#comment7 and b/181210044#comment8. So we have to roll it back.
https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/453 also roll back https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/452.
=> Revert "Set the default value of use_grpc back to true now that the grpc issue has been fixed. (#318)"

windows-installer/fluent-template.conf
Related underlying protobuf issue: https://github.com/protocolbuffers/protobuf/pull/8461.
More context: b/182381016#comment9
=> Set the default value of use_grpc back to true now that the google-protobuf issue has been fixed.

docker/Dockerfile
This reverts #336 and reinstates #335.
This reverts commit fa66b74a578575a6130fecf91887ae8f9c97369c.
A new version of the `add-logging-agent-repo.sh` script was released
that supports `DO_NOT_INSTALL_CATCH_ALL_CONFIG`.
=> Switch from install-logging-agent.sh to add-logging-agent-repo.sh.

config/software/fluentd.rb
Fixes https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/447#issuecomment-847187748
=> Revert Fluentd from 1.12.3 to 1.11.2 for memory / cpu regression.

config/software/fluentd.rb, windows-installer/generate_sdl_agent_exe.ps1
Follow up of https://github.com/GoogleCloudPlatform/google-fluentd/pull/340
=> Revert Fluentd version from 1.12.3 to 1.11.2 for Windows as well.

build/x86_64_centos6/Dockerfile, build/x86_64_centos7/Dockerfile, build/x86_64_centos8/Dockerfile, build/x86_64_debian/Dockerfile, build/x86_64_sles12/Dockerfile, build/x86_64_sles15/Dockerfile
This mitigates insecure behavior of piping a script from the internet directly into a shell.
b/192355502
=> Download the RVM installation script and verify checksum before running.

config/projects/google-fluentd.rb, config/software/td-agent.rb
http://b/195585297
Temporarily until https://github.com/sparklemotion/nokogiri/issues/2302 is fixed, to unblock nightly builds.
I was able to successfully build the agent with this change for each of the affected distros.
=> Temporarily pin Nokogiri version to fix el6/el7/sles12 builds.

config/projects/google-fluentd.rb
http://b/195756317
Reverts GoogleCloudPlatform/google-fluentd#350 since the fix for https://github.com/sparklemotion/nokogiri/issues/2302 was released in the latest [Nokogiri v1.12.3](https://github.com/sparklemotion/nokogiri/releases/tag/v1.12.3) (1.12.3 / 2021-08-06)
Tested on the 3 affected distros and all builds passed.
=> Revert "Temporarily pin Nokogiri version to fix el6/el7/sles12 builds."

Gemfile.lock
This updates `openssl` to `1.0.2y` and picks up fixes for [CVE-2021-23840](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-23840), [CVE-2020-1971](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-1971), and [CVE-2020-1968](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-1968).
=> Upgrade omnibus-software to pick up chef/omnibus-software#1400.

build/x86_64_centos6/Dockerfile
…on CentOS 6. This should fix the build issues that remained after #364.
Detailed explanations at https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ and https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/.
See https://www.mail-archive.com/openssl-users@openssl.org/msg90092.html for why version `1.0.1n` is used.
=> Force RVM to use the version of openssl that handles certificate chains.

config/patches/ruby/ruby-2.6.7_c99.patch, config/projects/google-fluentd.rb, config/software/ruby.rb
#371 was not enough.
Also cherry-pick a fix for Ruby build breakage.
b/216825879
=> Actually bump the embedded Ruby version to 2.6.9.

build/x86_64_centos6/Dockerfile, build/x86_64_centos7/Dockerfile, build/x86_64_centos8/Dockerfile
- Remove stray `yum update` commands
- Redirect CentOS 8 mirrors to the vault
- Add missing dependency on CentOS 8
See also Stackdriver/agent-packaging#128
=> Fix CentOS build Dockerfiles.

build/x86_64_centos6/Dockerfile, build/x86_64_centos7/Dockerfile, build/x86_64_centos8/Dockerfile
This was needed after removing `yum update` (#377).
=> Explicitly update ca-certificates in CentOS build Dockerfiles.

core_gems.rb
Depends on #375 being merged and pushed through our build infrastructure.
=> Upgrade to grpc-1.43.1, to match the latest fluent-plugin-google-cloud.

config/projects/google-fluentd.rb, config/software/ruby.rb
Fixes [b/237596577](http://b/237596577) | Update Ruby version from 2.6.9 to 2.6.10
This picks up a vulnerability fix for CVE-2022-28739
Soak test results look okay: [b/237596577#comment3](http://b/237596577#comment3)
=> Bump Ruby version from 2.6.9 to 2.6.10.

config/projects/google-fluentd.rb, config/software/openssl.rb, config/software/postgresql.rb
Fixes [b/238373633](http://b/238373633) (Update chef/omnibus-software version in google-fluentd to pick up newer OpenSSL version for CVE-2021-4160 and CVE-2022-0778). See the successful build in b/238373633#comment10
Upgrade openssl to pick up the following CVE fixes:
* https://nvd.nist.gov/vuln/detail/CVE-2021-4160: The issue only affects OpenSSL on MIPS platforms. Fixed in OpenSSL 3.0.1 (Affected 3.0.0). Fixed in OpenSSL 1.1.1m (Affected 1.1.1-1.1.1l). Fixed in OpenSSL 1.0.2zc
* https://nvd.nist.gov/vuln/detail/CVE-2022-0778: It was addressed in the releases of 1.1.1n and 3.0.2 on the 15th March 2022. Fixed in OpenSSL 3.0.2 (Affected 3.0.0,3.0.1). Fixed in OpenSSL 1.1.1n (Affected 1.1.1-1.1.1m). Fixed in OpenSSL 1.0.2zd (Affected 1.0.2-1.0.2zc).
* …
=> Override Openssl version to 1.1.1q and upgrade Postgres to 9.6.24

config/projects/google-fluentd.rb
https://github.com/GoogleCloudPlatform/google-fluentd/pull/385#issuecomment-1208306100 didn't update agent version which caused release job failure due to duplicate package version being released
=> Manually update google-fluentd.rb version to 1.9.9

build/x86_64_amzn-2016.09/Dockerfile, build/x86_64_centos6/Dockerfile, build/x86_64_centos7/Dockerfile, build/x86_64_centos8/Dockerfile, build/x86_64_debian/Dockerfile, build/x86_64_sles12/Dockerfile, build/x86_64_sles15/Dockerfile
The new ruby version requires xz to be installed.
=> Adding xz to the build images

build/x86_64_centos6/Dockerfile
Previous rpm is not available anymore, replacing the link with a live one.
=> Fix centos6 Dockerfile build

build/x86_64_sles12/Dockerfile
Build image generation is failing with:
Signature verification failed for file 'repomd.xml' from repository 'OSS Update'
Disabled that repo and added a new one from the list:
https://download.opensuse.org/distribution/leap/42.3/iso/openSUSE-Leap-42.3-DVD-x86_64.iso.mirrorlist
=> Add valid SLES12 repo

config/software/openssl.rb
The previous commit to add support for openssl1.1.1t (#402) missed the step of adding the checksum to the config. This PR adds the checksum for the openssl1.1.1t tar file.
The sha256 was acquired by the following steps:
```bash
curl -LO https://www.openssl.org/source/openssl-1.1.1t.tar.gz
sha256sum openssl-1.1.1t.tar.gz
```
=> Add checksum for openssl1.1.1t

docker/Dockerfile
This is one change necessary to get ARTIFACT_REGISTRY_REGION forwarded from our release automation tool all the way to the install script. I also need to change a file inside git-on-borg and some release automation files too.
=> Support ARTIFACT_REGISTRY_REGION build arg in Dockerfile

build/x86_64_amzn-2016.09/Dockerfile, build/x86_64_centos6/Dockerfile, build/x86_64_centos7/Dockerfile, build/x86_64_centos8/Dockerfile, build/x86_64_debian/Dockerfile, build/x86_64_sles12/Dockerfile, build/x86_64_sles15/Dockerfile, config/software/ruby.rb
Ruby 3.1.3 does not build on older platforms like CentOS 7 (https://bugs.ruby-lang.org/issues/19161), and there's no fix yet in 3.1.4.
[b/254273286](http://b/254273286).
=> Change default Ruby version to 3.1.2.

build/x86_64_centos7/Dockerfile, build/x86_64_centos8/Dockerfile, config/projects/google-fluentd.rb
Also add a missing package for the psych gem native extension.
A minor follow-up to #410. Turns out I didn't update all the places that contain the Ruby version.
[b/254273286](http://b/254273286).
=> Actually change default Ruby version to 3.1.2.

build/x86_64_centos6/Dockerfile
Basically, the same as one of the commits in #411, but for CentOS 6.
[b/276374852](http://b/276374852).
=> Add missing package for the psych gem native extension (CentOS 6).

config/software/jemalloc.rb, config/software/ruby.rb
The agent uses significantly more memory with Ruby 3 than with Ruby 2 — this is an attempt to alleviate that.
[b/254273286](http://b/254273286).
=> Compile Ruby with jemalloc to optimize memory usage.

config/software/fluentd.rb, windows-installer/generate_sdl_agent_exe.ps1
Tracker: [b/293350172](http://b/293350172)
There have been several memory leak fixes since v1.13.3. Updating the version and having this run using our soak tests will help us see if we see some improvements. 
Related PR: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/510
=> fluentd: update fluentd version to v1.16.2

Gemfile, plugin_gems.rb
[b/310663890](http://b/310663890)
Works around https://github.com/knu/ruby-unf_ext/issues/74.
=> Pin unf_ext to 0.0.8.2 to avoid compilation errors.

Gemfile, plugin_gems.rb
This reverts commit e7eeeefa7a0eaa71d2f3fbba88d24668e74b1da4.
The upstream issue (knu/ruby-unf_ext#74) has been fixed, and a new version of the `unf_ext` gem (0.0.9.1) has been released. The package now builds without the workaround.
[b/310663890](http://b/310663890)
=> Revert "Pin unf_ext to 0.0.8.2 to avoid compilation errors. (#426)"

config/projects/google-fluentd.rb
SLES-12 doesn't have/need this package.
=> Constrain systemd-sysvcompat to SUSE 15.x only

config/projects/google-fluentd.rb
Unfortunately this is causing too many compatibility problems on existing supported variants of SLES 15. For now, `systemd-sysvcompat` needs to be installed manually if running on an SP6-based variant.
[b/372000696](http://b/372000696)
=> Revert systemd-sysvcompat depedendency

build/x86_64_sles15/Dockerfile
SP1 is EOL and now ships a version of glibc that's too old to build google-fluentd (2.26 < 2.27). SP5 has a much newer version. Would like to avoid SP6 for now due to the amount of breaking changes it introduces.
Tested by successfully building the builder image locally and then using that to successfully build a package locally.
http://b/388874195
=> Upgrade SLES 15 builder image
